services:
  traefik:
    image: traefik:v3.5
    command:
      - --metrics.prometheus=true
      - --api.insecure=true
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
